### ISSUE TITLE
No 'Access-Control-Allow-Origin' header issue

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/bell#123]
I am getting:
```js
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.
```

I have tried probably everything (setting headers and stuff) but I still get the same error. I only want to load the oath flow in the same window but apparently that is not possible or am I doing something wrong here?

**Comment by ldesplat** [comment]
Can you elaborate on your issue a bit more. I have had no problem using the same window for OAuth flow by just putting a link to a configured hapi/bell endpoint.

This error I am pretty sure is coming on the browser? Where in the process is it doing it? On initial link to your endpoint? On redirect? Are you accessing your site using http://www.server but then doing the request with just http://server. Are you using javascript to do the request? Usually your /login endpoint is on the same domain as your main website but if it's not, then you just need Hapi to send the proper CORS header for it.

I hope that helps or gets you on your way. Feel free to post more details :)

**Comment by AdriVanHoudt** [comment]
Yes the browser is the problem. I am doing the request to the server with angular's `$http.get` and the server is on 127.0.0.1:8000 and client on 127.0.0.1:3500. I get the error on the redirect to the url of the auth provider. Doing it in `window.open` works fine, now trying an iframe

**Comment by ldesplat** [comment]
Should you not be using $location instead of doing $http.get. It does not make any sense to me doing the $http.get since Bell will redirect the user to the login endpoint of the auth provider. 

There, the user logs in and or is automatically seen as logged in (cookies, ...) and then the user is redirected back to our bell endpoint which uses the information in the redirect to ask for an access_token from the auth provider.

But if I am missing something with $http.get, I am pretty sure you have already tried sending CORS headers from Hapi which have the domain of the auth provider?

**Comment by AdriVanHoudt** [comment]
You are a god, works like a charm :pray: I almost had a mental breakdown on this today :worried: 
For a quick follow up question, any idea how I can get a hold of the original request url (client url) in the handler?
