### ISSUE TITLE
email not returned by facebook

### ISSUE THREAD

**Issue by chaiyitsheng** [hapijs/bell#144]
i have the following code 

		server.auth.strategy(providerName, 'bell', {
	        provider: providerName,
	        password: config.cookie.password,
	        clientId: config.login[providerName].clientId,
	        clientSecret: config.login[providerName].clientSecret,
	        scope:config.login[providerName].scope,
	        isSecure: false 
	    });
where the config.login[providerName].scope = ['public_profile','email','user_friends'].

It is not returning the email and user_friends....how do I go about this?

Thanks

**Comment by diego04** [comment]
user_friends: you will only see the person's friends if they are using your app as well. for email, sometimes it is null because the user used a cell phone number when they registered to facebook.com, if  you are using multiple facebook account and they all dont return an email, then im not sure

**Comment by chaiyitsheng** [comment]
hello, the facebook account used an email for registration and is enabled as the primary email. Login with  Google+ works perfectly and returns all the information requested in the scope. Maybe facebook has some filtering going on. Thanks anyway.

**Comment by ldesplat** [comment]
What version of Bell are you using? There were some changes in `5.0.1` but even then you should be getting the email. At least it does for me whenever I have tried which is every release since.

Did you also look at `raw` object at the same level as where `email` would be? Does it have what you need?

Also, you may have to specify
```
profileParams: {
    fields: 'id,name,email,...'
}
```

You can see what we include by default at https://github.com/hapijs/bell/blob/master/lib/providers/facebook.js#L24

Hope this helps. If you need more help, you can show what you get as response in the credentials object and the version of bell you are using.

**Comment by chaiyitsheng** [comment]
Hello, thanks everyone for the help, very kind of you. I had Bell version 1.1.0 (really old version installed), after switching to the latest version 5.x.x, everything is working and returning properly. 

Another question that's somewhat related to Bell, the facebook login returns an object profile in the following format.

profile:{
id:1xxxxxxxxxxxx,
email abc@xyz.com
}

which do you use as a primary key for a users database? given that facebook may change the id and the user can change the email at any time...

seems a little risky to use data from a facebook login to create a user record.

Appreciate your opinions. 

Thanks

**Comment by ldesplat** [comment]
Facebook has some really good documentation. For example [https://developers.facebook.com/docs/facebook-login/multiple-providers](https://developers.facebook.com/docs/facebook-login/multiple-providers) outlines some good strategies.

I personally, assign an id created by myself, use and verify their facebook email address (send an email). Then I exchange the token for a long lived one (since I don't use Bell for facebook auth but I go through the implicit auth instead) and store that along with the expiry time.
