### ISSUE TITLE
Allow passing custom wreck options

### ISSUE THREAD

**Issue by ldesplat** [hapijs/bell#218]
- trace headers (ie. a correlation header)
- timeout options
- anything else?

Somewhat of a bug, as not being able to specify timeout seems to be wrong...

Maybe allow users to pass in a wreck instance directly? Either way, will need to be able to be set per request.

**Comment by cvillerm** [comment]
I find this to be useful too to be able to pass TLS options to wreck if the Authorization Server is requesting client certificate-based authentication for calls to its token endpoint, instead of passing credentials as client_id+ client_secret. The client certificate and key could be passed as such options.
