### ISSUE TITLE
Allow different callback path when finished with the oauth flow

### ISSUE THREAD

**Issue by ldesplat** [hapijs/bell#219]
Some users want to handle the last part of the oauth flow at a different url. Right now, if a user starts at /login they will always be redirected back to /login.

**Comment by dltmd6262** [comment]
Is this still a valid feature request? I'm a new contributor and I would love to give a shot on it :]

**Comment by ldesplat** [comment]
@dltmd6262 Yes, it very much is a valid feature request. If you are still interested, feel free to ask questions or e-mail me directly if you don't feel comfortable.

I apologize for the late response and really hope that enthusiasm is still available :)

**Comment by dltmd6262** [comment]
Yup still here :] Please do give me some time to look over the code and I'll ask questions soon!

**Comment by dltmd6262** [comment]
Ok. So I read through the code and I think I have a question.
My first guess was that instead of reply.continue at the end of [v1](https://github.com/hapijs/bell/blob/687d49574b97ceb6628026780c3e9feca4168428/lib/oauth.js#L134) and [v2](https://github.com/hapijs/bell/blob/687d49574b97ceb6628026780c3e9feca4168428/lib/oauth.js#L305) I need to call reply.redirect with a uri.

But I'm not sure how I can pass the credentials data along with it. Am I going in the right direction?? Thanks!
