### ISSUE TITLE
Bell 8.0.0 Release Notes

### ISSUE THREAD

**Issue by ldesplat** [hapijs/bell#243]
## Breaking Change

If you use the Google provider, **it will not use Google+** to fetch user details anymore. If you want that functionality, then you muse use the `googleplus` which is the exact replica of the old google provider.

If you decide to continue using the `google` provider, do note that the profile response will look different and you must accommodate that change in your application.

See #228 and #235 

## Other Changes in this Release
- New Fitbit provider (see #240)
- `providerParams` and `scope` can now be synchronous functions that take in the request object and return an object to allow for more dynamic scenarios (see #233)
- Upgraded Joi to 9.x.x releases

---

Hapijs organization uses Milestones to track changes. Even though major releases, warrant release notes, you can access all the previous releases and changes here: https://github.com/hapijs/bell/milestones?state=closed

Thank you everyone!

**Comment by ericeslinger** [comment]
I just recently upgraded to bell 8 (I don't revise dependencies often, since breaking changes are never fun).

As feedback, it would have been a ton easier for me if you'd have kept the `google` provider the same, and created a new provider called `googleminus` or something. In that case, I wouldn't be getting the more slim request against google auth scopes, but I would also not be getting a differently-formatted response either, and my code would have Just Kept Working.
