### ISSUE TITLE
Cors issue in hapi

### ISSUE THREAD

**Issue by TelmaFernandes** [hapijs/bell#270]
Hello, 

I'm having the following error:

```
XMLHttpRequest cannot load {MY_SERVICE_PATH}. The request was redirected to 'https://www.facebook.com/v2.3/dialog/oauth?client_id=493482840803329&respon…irthday%2Cuser_education_history%2Cuser_events%2Cuser_likes%2Cmanage_pages', which is disallowed for cross-origin requests that require preflight.
```

Do you know what this might be and how to solve it? 
Thanks. :slightly_smiling_face:

**Comment by ldesplat** [comment]
The problem is that you used XMLHttpRequest to point to the login flow. Try doing a simple link or changing the url of the browser instead.

If you still want to do what you're doing, you will have to react those excellent docs: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

They explain everything a lot better than I ever could. If you have to setup additional cors headers, you can look at http://hapijs.com/api#route-options on how to do it. You can type cors in the search bar and it will show you exactly all the pertinent information.
