### ISSUE TITLE
How to integrate passwordless auth0 with bell?

### ISSUE THREAD

**Issue by rug1** [hapijs/bell#277]
I have setup my auth strategy as follows:
```javascript
    server.auth.strategy('auth0', 'bell', {
        provider: 'auth0',
        config: {
          domain: process.env.AUTH0_CLIENT_DOMAIN,
        },
        password: 'cookie_encryption_password_secure',
        clientId: process.env.AUTH0_CLIENT_ID,
        clientSecret: process.env.AUTH0_CLIENT_SECRET,
        isSecure: false     
    });
```
However, this only allows me to sign up/log in with only either google or email and password. I would really like to use the passwordless SMS method that auth0 provide. Is there a way I can integrate this with the bell strategy I have set up?

**Comment by sholladay** [comment]
I am also curious about this. My understanding is that the strategy config would be the same as usual but that we need to initiate the login flow in a different way on the client instead of relying upon `bell` to do so. I think this is because the Lock widget doesn't determine password vs passwordless at runtime (they are implemented as two different classes). Perhaps because this is considered an edge case so they don't bother using the network like they do for determining which social providers are enabled (just guessing).

This brings up the larger issue of customization using `auth0` and `bell` together. E.g. I also don't know how I would set the [socialButtonStyle](https://auth0.com/docs/libraries/lock/v10/customization#socialbuttonstyle-string-) or other Lock options used at `my-app.auth0.com/login`.

Maybe @rolodato can point us in the right direction.

**Comment by rolodato** [comment]
This is a bit more complicated than we'd like it to be. We don't have any examples that implement passwordless authentication using a standard OAuth library, but technically I think it should be possible.

The reason why Auth0 does not display passwordless authentication as an option when redirecting to /authorize is, as @sholladay mentioned, because Lock for passwordless is [implemented as a separate module](https://github.com/auth0/lock-passwordless). We plan on bringing the two Locks together, but this won't be happening any time soon. That being said, it's not mandatory to use Lock, and you can fully customize the login page HTML here: https://manage.auth0.com/#/login_page

I believe the only type of passwordless authentication you'll be able to implement with bell is email magic links, because they have the capability of invoking bell's callback endpoint with an OAuth authorization `code`. The other types (email code and SMS code) are implemented as non-standard credential exchanges (i.e. make a request to `/oauth/ro` with a OTP, get back tokens). Since these are not strictly OAuth, I don't see a reason why bell should be implementing them. We do plan on improving this situation as well.

If you do manage to get an Auth0 login page set up for magic links, you'll need to make sure the request to `/passwordless/start` sends the proper `state` parameter (bell generates and validates this for you automatically). You can send `authParams.state` in the request body to determine which `state` parameter will be sent back to bell. The default Auth0 login page has a `config` variable - you can use `config.internalOptions.state` to access it.

**Comment by sholladay** [comment]
Very insightful, thanks a lot!

So the summary is this generally won't work because:
 - It is a non-standard flow that is possibly out-of-scope for `bell`.
 - The default HTML imports the wrong variant of Lock for this use case (but is customizable).

Hopefully someone is able to cook up a recipe for email magic links as described above.

**Comment by rug1** [comment]
Thanks @sholladay and @rolodato! Very helpful!
