### ISSUE TITLE
Internal server error on facebook provider

### ISSUE THREAD

**Issue by captainjackrana** [hapijs/bell#287]
My issue is pretty similar to [https://github.com/hapijs/bell/issues/4](url), however, since there was no conclusion drawn, so posting it fresh..

After authenticating via facebook login, upon redirection back to my server, hapi throws a 500 internal server error. 
The callback url is supposed to be /login/facebook
Following is the output of request.getLog()

`request=1483986677837:ip-172-31-4-122:3927:ixqbcbzc:39617, timestamp=1483986677837, tags=[received], method=get, url=/login/facebook?code=AQCqizbE7s2hK5HA_nHKcbvPZxB6cuYTtujg4naKnPYsYVFMguNMJzsw-8YblHcpv9-kXx1NnCh1mG-c6odKAg5jnB7PCOHgXe2rek1gS9QQTNpJCEeEzrKwJvUlotjtWaRK2OUvNwPzTHIOXDpmxC-eno7wmtHteBd-mBt--1ragkXJDDKEFQa-xYuLl6TqBZ5WtjEirr7I2Syt_4eab7d3s2r8DtkvqPo2kjYkUB-4zAVnVgN2T-9gYZD667xxF8I4HD&state=zQJynY1m61sPHsvolrpjBv&refresh=1, agent=Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko; googleweblight) Chrome/38.0.1025.166 Mobile Safari/535.19, internal=true, request=1483986677837:ip-172-31-4-122:3927:ixqbcbzc:39617, timestamp=1483986677838, tags=[auth, unauthenticated, error, fb], data=undefined, isBoom=true, isServer=true, statusCode=500, statusCode=500, error=Internal Server Error, message=An internal server error occurred,`

From the tags list in the log above, it looks like the request is unauthenticated, which is weird since the user has authenticated on facebook. 
An additional note - this happens for roughly 10% of the people who login.. the rest are able to successfully authenticate and proceed

 The configuration for bell facebook provider - 

`{

        provider: 'facebook',
        password: config.pass,
        clientId: config.api.fb.appId,
        clientSecret: config.api.fb.appSecret,
        isSecure: false, //Should be set to true (which is the default) in production
        scope: ['public_profile', 'email', 'user_birthday', 'user_work_history']
    }`

**Comment by ahmedNY** [comment]
i had the same issue :(

**Comment by captainjackrana** [comment]
Okay.. after going through previous logged issues, i can link my problem to https://github.com/hapijs/bell/issues/191
The ticket says it was fixed in 7.6.1, while i'm on bell 8.0.0
It only happens for Safari browsers.. Some of the user agent strings that encountered this problem - 

- Mozilla/5.0 (iPhone; CPU iPhone OS 10_1_1 like Mac OS X) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0 Mobile/14B100 Safari/602.1

- AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

-  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

- (Linux; Android 4.4.2; Atom 2 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36

**Comment by ldesplat** [comment]
Thank you for showing this. I don't have access to a production bell anymore so I don't get to see those issues. 

Chrome 55 and Safari 10, interesting. There was this PR https://github.com/hapijs/bell/pull/265 to resolve the issue with the cookies not being sent + the PR you linked.

So since #265 is 8.5.0 I would recommend you upgrade bell?

**Comment by captainjackrana** [comment]
Updated to 8.5.0 and observed for a day.. Still getting the same errors on the same set of user agent strings 
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by sholladay** [comment]
I would bet that those users are hitting "deny" / "cancel" on the Facebook confirmation screen. If they do, a 500 error is expected (even though it's not ideal).

Here is what you should do:

1. Set the `mode` of your login route to `try` so that you can inspect authentication errors.
2. In the handler, log the value of `request.auth.error.message`.
3. Open your browser and try to login using the route, but hit cancel on the Facebook confirmation screen.

You should now see something like `App rejected: Permissions error` in your logs, but still a generic 500 on the client. This is what I believe is happening to your users. There are two main reasons they might deny access, either you are asking for too many permissions or they made a mistake. For example, they may have hit the wrong button either on Facebook or in your app or perhaps they realized they are logged into the wrong Facebook account.

Below is an example of what I do to deal with this. You will want to change the strategy name and if you are not using [hapi-auth-cookie](https://github.com/hapijs/hapi-auth-cookie), replace `request.cookieAuth` with some other way to start the session.

Note that `App rejected:` is the only stable, reliable part of the message string, because it [comes from bell](https://github.com/hapijs/bell/blob/bd3702d2a37d7cdaf55ef0df2c838dc291d21bb2/lib/oauth.js#L153), hence the `startsWith()` check. For the second part, Google says `unauthorized user` whereas Facebook says `Permissions error`, for example.

```js
server.route({
    method : 'GET',
    path   : '/login',
    config : {
        tags        : ['user', 'auth', 'session', 'login'],
        description : 'Begin a user session.',
        auth        : {
            strategy : 'auth0',
            mode     : 'try'
        }
    },
    handler(request, reply) {
        if (request.auth.isAuthenticated) {
            request.cookieAuth.set({ user : request.auth.credentials.profile });
            reply.redirect('/');
        }
        // This happens when users deny us access to their OAuth provider.
        else if (request.auth.error.message.startsWith('App rejected')) {
            // Give the user another chance to login.
            reply.redirect('/login');
        }
        else {
            reply(boom.unauthorized(request.auth.error.message));
        }
    }
});
```

**Comment by captainjackrana** [comment]
@sholladay That was my first assumption too.. I have been using `auth:{mode: 'try'}` and logging two types of errors primarily.
`error: Error authenticating Missing facebook request token cookie`
`error: Error authenticating App rejected: the user denied your request`

Another theory could be that people are hitting the back button post a successful login, during which the route handler `/login` does not find the token valid. I'd appreciate any ideas on how to handle cases like these

**Comment by sholladay** [comment]
I don't know how to handle the back button case and I'm curious about that too!

However, your second error message suggests that I was spot on. That is a user who went to log in but then denied permission on Facebook. I edited my comment above to add further details on that, it's pretty normal. I have a very clean UX where it just reloads the log in page whenever they do that, as it's usually a mistake. See the code above.

Your first error message looks exactly like what I have seen when the user takes their sweet time completing the log in process. To reproduce, just start the OAuth flow and only hit "Continue" on Facebook like 3 minutes later. Just need to track down which cookie has the short TTL.

**Comment by hueniverse** [comment]
If you need help with dealing with back button (user going back to the page where they hit login), there are ways to deal with that by using two auth schemes, one with bell and one with a cookie that signals bell was successful.
