### ISSUE TITLE
Passing a custom parameter through the auth process

### ISSUE THREAD

**Issue by ramiel** [hapijs/bell#305]
I have this scenario. A client want to login through a social provider and want information back through a redirect.
For example it will call
`http://api.com/login/facebook?redirect=http://client.com/onAuth`
the server, after logging in with facebook should do a redirect to `http://client.com/onAuth` passing the response through the query, so for example `http://client.com/onAuth?token=xxx`.    
Is that possible? I noticed  can intercept initial request and modify the state through `runtimeStateCallback` but this only let me append a string to the state query parameter. So I have to choose a separator to understand which data are mine and so on. Is there a way to add an entire new query parameter to the callback uri?
Is there a better method?

**Comment by ericeslinger** [comment]
I want to do something similar, except that I want to add an invariant parameter per-user to the login flow. 

Basically I want to attach a nonce to a login route like `login/google?reqid=1234`, and then sometime in the end of the OAUTH dance be able to grab the value of `reqid` back out of the data. I'm dealing with logging in to a standalone app via a web browser.

I can't use a captive browser in the app to grab the appropriate information because in cordova I don't get the `message` DOM event on captive browsers (and it's unclear if we'll be able to load google in a captive browser anyway.

1. user needs to log in, the client generates a nonce, and sends the nonce to the server via a websocket.
1. app shows "click here to log in" button, which opens a regular browser window using `target="_system"` in mobile devices, that includes ?nonce=whatever at the end of the URL.
1. after the OAUTH login dance, once the user is successfully authenticated and I have an API token on my server, the server's websocket engine replies to the socket that had sent the appropriate nonce request when the request started.

This does have the security hole of exposing a nonce in a URL parameter, but as long as they're short-lived (and the connection is https), the danger is pretty minimal (no more dangerous than anything else done with tokens at least, the attack surface is smaller than if someone MitMs the token). 

But the problem is that I need to keep that nonce, so when bell is done with the oauth dance, it can pass the nonce back to the handler that finalizes the login. I could maybe muck around with an internal redirect that sets a cookie (turn the get url into a post, just adding another step to the oauth dance) which stores the nonce, I think that will work, but it would just be easier to attach a parameter somewhere in the process.

**Comment by sholladay** [comment]
I think you want something like what I am doing with the `next` parameter in [hapi-doorkeeper](https://github.com/sholladay/hapi-doorkeeper/blob/46348cd1b9bbbcb89b1c44c81ef29d4a25f6876f/index.js#L70).

When the server receives a request at `my-site.com/login?foo=bar`, assuming `/login` is a route using `bell`, the route handler won't have `foo` in `request.query` because of the OAuth flow. But the original query is stored in `request.credentials.query`, so you have access to both and can do whatever you need with them.

**Comment by ericeslinger** [comment]
Mmm, yes, that's what I want.

I worked around this by adding an extra step to the login flow. I wrote my own general-purpose login redirector that the client hits at `/login?provider=google-oauth&nonce=foo`. That handler sets a cookie with the nonce and redirects to `/login/google-oauth` (my bell endpoint for google). The result handler checks the cookie for the user-generated nonce. It's not quite as scalable as providing access to the entire original querystring (and that would be quite useful, really), but it gets the job done.

example code can be found here:

* [redirector](https://github.com/ericeslinger/plump-strut/blob/master/src/authentication.ts#L97)
* [bell success handler](https://github.com/ericeslinger/plump-strut/blob/master/src/authentication.ts#L54)

there's a websocket thing going on in there, as that is how I communicate success back to the client - two channels so I can avoid limitations on using the captive browser for oauth logins in cordova apps.

**Comment by dpmott** [comment]
I had the same problem, and wished that hapi bell provided an accessor to get my state back out that I had supplied with `runtimeStateCallback`.  

It turns out that you can get the nonce that bell used (it's under a provider-specific key in the request.state), and then remove it from the request.query.state (which has the state you want).

In the route handler, I added these two lines:
```
          const nonce = request.state[Object.keys(request.state)[0]].nonce;
          const path = request.query.state.replace(nonce, '');
```

Now `path` has exactly what you had passed into `runtimeStateCallback`.  No need for delimiters.

**Comment by hueniverse** [comment]
Is there a reason this needs to use the runtime mechanism vs the original query passed to the endpoint and then passed back via `credentials.query`?

**Comment by ilyaigpetrov** [comment]
I don't quite understand the details, but here author suggests using state instead of query parameter for security reasons:

>The “state” parameter is intended to preserve some state object set by the client in the Authorization request, and make it available to the client in the response.  The main security reason for this is to stop Cross Site Request Forgery (XRSF).

["The correct use of the state parameter in OAuth 2"](http://www.thread-safe.com/2014/05/the-correct-use-of-state-parameter-in.html) by John B. aka ve7jtb

**Comment by AdriVanHoudt** [comment]
What is the actual request here?
Does using `request.auth.credentials.query` in your bell handler solve your issue @ramiel?

**Comment by ramiel** [comment]
Sorry, this issue is too old. I even forgot what it was about. I don't close this issue since I see it generated a discussion.

**Comment by AdriVanHoudt** [comment]
@ramiel no problem! If any else still has a question or a request please state so otherwise I will close this issue soon.

**Comment by sholladay** [comment]
I think this can be closed @AdriVanHoudt. I'm almost certain the answer to the original question is just to use `credentials.query` instead of `request.query` when you need access to the original, pre-`bell` query parameters.
