### ISSUE TITLE
Proposal: remove providers from this repo

### ISSUE THREAD

**Issue by cjihrig** [hapijs/bell#343]
I think removing the providers would make the codebase a lot smaller and make tasks like updating to hapi 17 smoother. Providers could live on their own, even outside of the hapijs org.

I think this would have a side effect of making this repo more manageable for a maintainer. My guess is that supporting ~40 providers (that are difficult to test) in this repo has lead to maintainer burnout/frustration.

**Comment by hueniverse** [comment]
I have mixed feelings about this idea. It does make bell a lot simpler to maintain but it just moved the problem elsewhere. Instead of having one place to deal with these issues, we'll have dozens and a much higher likelihood of stale and outdated plugins. If you consider the migration to hapi 17, I had to update each provider code to use an async profile function. This would have been a nightmare if I needed to coordinate that with multiple maintainers...

I don't think we have much choice but to keep trying to maintainer these providers as people identify problems. We can't really automate testing them in a production settings.
