### ISSUE TITLE
Facebook provider is throwing an error

### ISSUE THREAD

**Issue by alexgorbatchev** [hapijs/bell#4]
I'm getting this 

```
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
```

when being redirected from facebook back to `http://localhost:8080/auth/facebook?code=AQBfow3ErUA7-TB7N...`

no stack trace in the console :( will try to investigate tomorrow...

here's my setup

```
register = (plugin, options, next) ->
  plugin.register require('bell'), (err) ->
    plugin.auth.strategy 'facebook', 'bell',
      provider: 'facebook'
      password: '12345'
      clientId: settings.get 'facebook.appId'
      clientSecret: settings.get 'facebook.appSecret'

    plugin.route
      method: ['GET', 'POST']
      path: '/facebook'
      config:
        auth: 'facebook'
        handler: (request, reply) ->
          console.log request
          # // Perform any account lookup or registration, setup local session,
          # // and redirect to the application. The third-party credentials are
          # // stored in request.auth.credentials. Any query parameters from
          # // the initial request are passed back via request.auth.credentials.query.
          reply.redirect '/admin'

    next()
```

**Comment by nikhilaravi** [comment]
I'm getting exactly the same error but for Github login and I have already set isSecure to false. I am following this code exactly (https://gist.github.com/arb/9a1d8e694bbd12d5b455) but it is not working for any of the providers

**Comment by lintuxt** [comment]
I'm having the same issue and also I have already set isSecure to false.

**Comment by hueniverse** [comment]
Commenting on a year old issue is unlikely to get you help. You need to open a new issue with more specifics about what you are trying to do and the errors you are getting. Keep in mind that because of the many settings all around, helping you debug authentication is notoriously hard (and this code clearly works for a lot of people). So you will need to work extra hard to help people reproduce your specific issue.

**Comment by gabceb** [comment]
FWIW, we are experiencing a similar issue with Bell (Google as a provider) if we take too long to respond to the request that has an auth of `'google', 'bell'` because it fires the request to Google twice. Disclaimer: we are running a very old Bell (1.3.1) and Hapi (6.1.11) so feel free to discard if it works in newer builds.

To repro this with newer versions you can add a long timeout to the end of handler for the route and see if it happens

**Comment by phoenixbox** [comment]
I was experiencing this error when I realized that my `location` param did not match my referrer.

I was hitting auth from `localhost:3600` and my location param was set to `local.#{myApp}:3600` which I had aliased to localhost in my `etc/hosts`. Maybe the location param is the source of error for others

```
server.auth.strategy('${provider}', 'bell', {
      isSecure: false,
      provider: oauthConfig,
      password: config.cookie_password,
      clientId: config.client_id,
      clientSecret: config.client_secret,
      location: config.redirect_uri
    });
```
