### ISSUE TITLE
bell dependancy on http://passportjs.org

### ISSUE THREAD

**Issue by OwenBrotherwood** [hapijs/bell#95]
A dependancy on http://passportjs.org/ to obtain support for other providers/strategies.
- "mainstream" providers/strategies that are lacking in bell could be implemented as need arises without a dependancy on passport.
  - https://github.com/hapijs/bell/issues/55#issuecomment-74349084

---

Notes:
- passport has no dependancy on express: [package.json](https://github.com/jaredhanson/passport/blob/master/package.json?#L33-36)

---
Side issues: 
- https://github.com/hapijs/bell/issues/55
- https://github.com/hapijs/bell/issues/18

Downstream issues:
- https://github.com/hapijsing/hapijsing-issues/issues/4

**Comment by ldesplat** [comment]
I am going to refer to the following modules:

Deprecated but bell ancestor: https://github.com/hapijs/travelogue
No idea how good it is: https://github.com/ikkyotech/hapi-passport

Both use or used Passport. If you want to know why you can ping the original people and ask them. Because of that I'll close this issue now.

Though I fully agree that I would love to see SAML, LDAP support amongst others.
